// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CS.CSPasswdLoginMsg.proto

package com.empire.msg.cs;

public final class CSCSPasswdLoginMsg {
  private CSCSPasswdLoginMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CSPasswdLoginMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 deviceType = 1;
    /**
     * <code>optional int32 deviceType = 1;</code>
     */
    boolean hasDeviceType();
    /**
     * <code>optional int32 deviceType = 1;</code>
     */
    int getDeviceType();

    // optional string accountName = 2;
    /**
     * <code>optional string accountName = 2;</code>
     */
    boolean hasAccountName();
    /**
     * <code>optional string accountName = 2;</code>
     */
    java.lang.String getAccountName();
    /**
     * <code>optional string accountName = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccountNameBytes();

    // optional string passwd = 3;
    /**
     * <code>optional string passwd = 3;</code>
     */
    boolean hasPasswd();
    /**
     * <code>optional string passwd = 3;</code>
     */
    java.lang.String getPasswd();
    /**
     * <code>optional string passwd = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswdBytes();

    // optional string deviceId = 4;
    /**
     * <code>optional string deviceId = 4;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>optional string deviceId = 4;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>optional string deviceId = 4;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();
  }
  /**
   * Protobuf type {@code com.empire.msg.cs.CSPasswdLoginMsg}
   */
  public static final class CSPasswdLoginMsg extends
      com.google.protobuf.GeneratedMessage
      implements CSPasswdLoginMsgOrBuilder {
    // Use CSPasswdLoginMsg.newBuilder() to construct.
    private CSPasswdLoginMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CSPasswdLoginMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CSPasswdLoginMsg defaultInstance;
    public static CSPasswdLoginMsg getDefaultInstance() {
      return defaultInstance;
    }

    public CSPasswdLoginMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CSPasswdLoginMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              deviceType_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              accountName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              passwd_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              deviceId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.empire.msg.cs.CSCSPasswdLoginMsg.internal_static_com_empire_msg_cs_CSPasswdLoginMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.empire.msg.cs.CSCSPasswdLoginMsg.internal_static_com_empire_msg_cs_CSPasswdLoginMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg.class, com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<CSPasswdLoginMsg> PARSER =
        new com.google.protobuf.AbstractParser<CSPasswdLoginMsg>() {
      public CSPasswdLoginMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSPasswdLoginMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CSPasswdLoginMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 deviceType = 1;
    public static final int DEVICETYPE_FIELD_NUMBER = 1;
    private int deviceType_;
    /**
     * <code>optional int32 deviceType = 1;</code>
     */
    public boolean hasDeviceType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 deviceType = 1;</code>
     */
    public int getDeviceType() {
      return deviceType_;
    }

    // optional string accountName = 2;
    public static final int ACCOUNTNAME_FIELD_NUMBER = 2;
    private java.lang.Object accountName_;
    /**
     * <code>optional string accountName = 2;</code>
     */
    public boolean hasAccountName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string accountName = 2;</code>
     */
    public java.lang.String getAccountName() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accountName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string accountName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string passwd = 3;
    public static final int PASSWD_FIELD_NUMBER = 3;
    private java.lang.Object passwd_;
    /**
     * <code>optional string passwd = 3;</code>
     */
    public boolean hasPasswd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string passwd = 3;</code>
     */
    public java.lang.String getPasswd() {
      java.lang.Object ref = passwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          passwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string passwd = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswdBytes() {
      java.lang.Object ref = passwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string deviceId = 4;
    public static final int DEVICEID_FIELD_NUMBER = 4;
    private java.lang.Object deviceId_;
    /**
     * <code>optional string deviceId = 4;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string deviceId = 4;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deviceId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      deviceType_ = 0;
      accountName_ = "";
      passwd_ = "";
      deviceId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, deviceType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccountNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPasswdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDeviceIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, deviceType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccountNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPasswdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDeviceIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.empire.msg.cs.CSPasswdLoginMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.empire.msg.cs.CSCSPasswdLoginMsg.internal_static_com_empire_msg_cs_CSPasswdLoginMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.empire.msg.cs.CSCSPasswdLoginMsg.internal_static_com_empire_msg_cs_CSPasswdLoginMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg.class, com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg.Builder.class);
      }

      // Construct using com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        accountName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        passwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.empire.msg.cs.CSCSPasswdLoginMsg.internal_static_com_empire_msg_cs_CSPasswdLoginMsg_descriptor;
      }

      public com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg getDefaultInstanceForType() {
        return com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg.getDefaultInstance();
      }

      public com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg build() {
        com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg buildPartial() {
        com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg result = new com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceType_ = deviceType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accountName_ = accountName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.passwd_ = passwd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.deviceId_ = deviceId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg) {
          return mergeFrom((com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg other) {
        if (other == com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg.getDefaultInstance()) return this;
        if (other.hasDeviceType()) {
          setDeviceType(other.getDeviceType());
        }
        if (other.hasAccountName()) {
          bitField0_ |= 0x00000002;
          accountName_ = other.accountName_;
          onChanged();
        }
        if (other.hasPasswd()) {
          bitField0_ |= 0x00000004;
          passwd_ = other.passwd_;
          onChanged();
        }
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000008;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.empire.msg.cs.CSCSPasswdLoginMsg.CSPasswdLoginMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 deviceType = 1;
      private int deviceType_ ;
      /**
       * <code>optional int32 deviceType = 1;</code>
       */
      public boolean hasDeviceType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 deviceType = 1;</code>
       */
      public int getDeviceType() {
        return deviceType_;
      }
      /**
       * <code>optional int32 deviceType = 1;</code>
       */
      public Builder setDeviceType(int value) {
        bitField0_ |= 0x00000001;
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 deviceType = 1;</code>
       */
      public Builder clearDeviceType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceType_ = 0;
        onChanged();
        return this;
      }

      // optional string accountName = 2;
      private java.lang.Object accountName_ = "";
      /**
       * <code>optional string accountName = 2;</code>
       */
      public boolean hasAccountName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string accountName = 2;</code>
       */
      public java.lang.String getAccountName() {
        java.lang.Object ref = accountName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          accountName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string accountName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccountNameBytes() {
        java.lang.Object ref = accountName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string accountName = 2;</code>
       */
      public Builder setAccountName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accountName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string accountName = 2;</code>
       */
      public Builder clearAccountName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accountName_ = getDefaultInstance().getAccountName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string accountName = 2;</code>
       */
      public Builder setAccountNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accountName_ = value;
        onChanged();
        return this;
      }

      // optional string passwd = 3;
      private java.lang.Object passwd_ = "";
      /**
       * <code>optional string passwd = 3;</code>
       */
      public boolean hasPasswd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string passwd = 3;</code>
       */
      public java.lang.String getPasswd() {
        java.lang.Object ref = passwd_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          passwd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string passwd = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswdBytes() {
        java.lang.Object ref = passwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          passwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string passwd = 3;</code>
       */
      public Builder setPasswd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        passwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string passwd = 3;</code>
       */
      public Builder clearPasswd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        passwd_ = getDefaultInstance().getPasswd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string passwd = 3;</code>
       */
      public Builder setPasswdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        passwd_ = value;
        onChanged();
        return this;
      }

      // optional string deviceId = 4;
      private java.lang.Object deviceId_ = "";
      /**
       * <code>optional string deviceId = 4;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string deviceId = 4;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deviceId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deviceId = 4;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceId = 4;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceId = 4;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.empire.msg.cs.CSPasswdLoginMsg)
    }

    static {
      defaultInstance = new CSPasswdLoginMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.empire.msg.cs.CSPasswdLoginMsg)
  }

  public interface CSBindAccountMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string accountName = 1;
    /**
     * <code>optional string accountName = 1;</code>
     */
    boolean hasAccountName();
    /**
     * <code>optional string accountName = 1;</code>
     */
    java.lang.String getAccountName();
    /**
     * <code>optional string accountName = 1;</code>
     */
    com.google.protobuf.ByteString
        getAccountNameBytes();

    // optional string passwd = 2;
    /**
     * <code>optional string passwd = 2;</code>
     */
    boolean hasPasswd();
    /**
     * <code>optional string passwd = 2;</code>
     */
    java.lang.String getPasswd();
    /**
     * <code>optional string passwd = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswdBytes();
  }
  /**
   * Protobuf type {@code com.empire.msg.cs.CSBindAccountMsg}
   */
  public static final class CSBindAccountMsg extends
      com.google.protobuf.GeneratedMessage
      implements CSBindAccountMsgOrBuilder {
    // Use CSBindAccountMsg.newBuilder() to construct.
    private CSBindAccountMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CSBindAccountMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CSBindAccountMsg defaultInstance;
    public static CSBindAccountMsg getDefaultInstance() {
      return defaultInstance;
    }

    public CSBindAccountMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CSBindAccountMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              accountName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              passwd_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.empire.msg.cs.CSCSPasswdLoginMsg.internal_static_com_empire_msg_cs_CSBindAccountMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.empire.msg.cs.CSCSPasswdLoginMsg.internal_static_com_empire_msg_cs_CSBindAccountMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg.class, com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<CSBindAccountMsg> PARSER =
        new com.google.protobuf.AbstractParser<CSBindAccountMsg>() {
      public CSBindAccountMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSBindAccountMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CSBindAccountMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string accountName = 1;
    public static final int ACCOUNTNAME_FIELD_NUMBER = 1;
    private java.lang.Object accountName_;
    /**
     * <code>optional string accountName = 1;</code>
     */
    public boolean hasAccountName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string accountName = 1;</code>
     */
    public java.lang.String getAccountName() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accountName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string accountName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string passwd = 2;
    public static final int PASSWD_FIELD_NUMBER = 2;
    private java.lang.Object passwd_;
    /**
     * <code>optional string passwd = 2;</code>
     */
    public boolean hasPasswd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string passwd = 2;</code>
     */
    public java.lang.String getPasswd() {
      java.lang.Object ref = passwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          passwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string passwd = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswdBytes() {
      java.lang.Object ref = passwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      accountName_ = "";
      passwd_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAccountNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAccountNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.empire.msg.cs.CSBindAccountMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.empire.msg.cs.CSCSPasswdLoginMsg.internal_static_com_empire_msg_cs_CSBindAccountMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.empire.msg.cs.CSCSPasswdLoginMsg.internal_static_com_empire_msg_cs_CSBindAccountMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg.class, com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg.Builder.class);
      }

      // Construct using com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accountName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        passwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.empire.msg.cs.CSCSPasswdLoginMsg.internal_static_com_empire_msg_cs_CSBindAccountMsg_descriptor;
      }

      public com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg getDefaultInstanceForType() {
        return com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg.getDefaultInstance();
      }

      public com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg build() {
        com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg buildPartial() {
        com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg result = new com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountName_ = accountName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.passwd_ = passwd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg) {
          return mergeFrom((com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg other) {
        if (other == com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg.getDefaultInstance()) return this;
        if (other.hasAccountName()) {
          bitField0_ |= 0x00000001;
          accountName_ = other.accountName_;
          onChanged();
        }
        if (other.hasPasswd()) {
          bitField0_ |= 0x00000002;
          passwd_ = other.passwd_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.empire.msg.cs.CSCSPasswdLoginMsg.CSBindAccountMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string accountName = 1;
      private java.lang.Object accountName_ = "";
      /**
       * <code>optional string accountName = 1;</code>
       */
      public boolean hasAccountName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string accountName = 1;</code>
       */
      public java.lang.String getAccountName() {
        java.lang.Object ref = accountName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          accountName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string accountName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAccountNameBytes() {
        java.lang.Object ref = accountName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string accountName = 1;</code>
       */
      public Builder setAccountName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accountName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string accountName = 1;</code>
       */
      public Builder clearAccountName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountName_ = getDefaultInstance().getAccountName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string accountName = 1;</code>
       */
      public Builder setAccountNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accountName_ = value;
        onChanged();
        return this;
      }

      // optional string passwd = 2;
      private java.lang.Object passwd_ = "";
      /**
       * <code>optional string passwd = 2;</code>
       */
      public boolean hasPasswd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public java.lang.String getPasswd() {
        java.lang.Object ref = passwd_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          passwd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswdBytes() {
        java.lang.Object ref = passwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          passwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public Builder setPasswd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        passwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public Builder clearPasswd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        passwd_ = getDefaultInstance().getPasswd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public Builder setPasswdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        passwd_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.empire.msg.cs.CSBindAccountMsg)
    }

    static {
      defaultInstance = new CSBindAccountMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.empire.msg.cs.CSBindAccountMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_empire_msg_cs_CSPasswdLoginMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_empire_msg_cs_CSPasswdLoginMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_empire_msg_cs_CSBindAccountMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_empire_msg_cs_CSBindAccountMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031CS.CSPasswdLoginMsg.proto\022\021com.empire." +
      "msg.cs\032\014struct.proto\"]\n\020CSPasswdLoginMsg" +
      "\022\022\n\ndeviceType\030\001 \001(\005\022\023\n\013accountName\030\002 \001(" +
      "\t\022\016\n\006passwd\030\003 \001(\t\022\020\n\010deviceId\030\004 \001(\t\"7\n\020C" +
      "SBindAccountMsg\022\023\n\013accountName\030\001 \001(\t\022\016\n\006" +
      "passwd\030\002 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_empire_msg_cs_CSPasswdLoginMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_empire_msg_cs_CSPasswdLoginMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_empire_msg_cs_CSPasswdLoginMsg_descriptor,
              new java.lang.String[] { "DeviceType", "AccountName", "Passwd", "DeviceId", });
          internal_static_com_empire_msg_cs_CSBindAccountMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_empire_msg_cs_CSBindAccountMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_empire_msg_cs_CSBindAccountMsg_descriptor,
              new java.lang.String[] { "AccountName", "Passwd", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.empire.msg.Struct.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
