// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CS.CSQuickLoginMsg.proto

package com.empire.msg.auto.cs;

public final class CSCSQuickLoginMsg {
  private CSCSQuickLoginMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CSQuickLoginMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 deviceType = 1;
    /**
     * <code>optional int32 deviceType = 1;</code>
     */
    boolean hasDeviceType();
    /**
     * <code>optional int32 deviceType = 1;</code>
     */
    int getDeviceType();

    // optional string deviceId = 2;
    /**
     * <code>optional string deviceId = 2;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>optional string deviceId = 2;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>optional string deviceId = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();
  }
  /**
   * Protobuf type {@code com.empire.msg.auto.cs.CSQuickLoginMsg}
   */
  public static final class CSQuickLoginMsg extends
      com.google.protobuf.GeneratedMessage
      implements CSQuickLoginMsgOrBuilder {
    // Use CSQuickLoginMsg.newBuilder() to construct.
    private CSQuickLoginMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CSQuickLoginMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CSQuickLoginMsg defaultInstance;
    public static CSQuickLoginMsg getDefaultInstance() {
      return defaultInstance;
    }

    public CSQuickLoginMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CSQuickLoginMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              deviceType_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              deviceId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.empire.msg.auto.cs.CSCSQuickLoginMsg.internal_static_com_empire_msg_auto_cs_CSQuickLoginMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.empire.msg.auto.cs.CSCSQuickLoginMsg.internal_static_com_empire_msg_auto_cs_CSQuickLoginMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg.class, com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<CSQuickLoginMsg> PARSER =
        new com.google.protobuf.AbstractParser<CSQuickLoginMsg>() {
      public CSQuickLoginMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSQuickLoginMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CSQuickLoginMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 deviceType = 1;
    public static final int DEVICETYPE_FIELD_NUMBER = 1;
    private int deviceType_;
    /**
     * <code>optional int32 deviceType = 1;</code>
     */
    public boolean hasDeviceType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 deviceType = 1;</code>
     */
    public int getDeviceType() {
      return deviceType_;
    }

    // optional string deviceId = 2;
    public static final int DEVICEID_FIELD_NUMBER = 2;
    private java.lang.Object deviceId_;
    /**
     * <code>optional string deviceId = 2;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string deviceId = 2;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deviceId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      deviceType_ = 0;
      deviceId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, deviceType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDeviceIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, deviceType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDeviceIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.empire.msg.auto.cs.CSQuickLoginMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.empire.msg.auto.cs.CSCSQuickLoginMsg.internal_static_com_empire_msg_auto_cs_CSQuickLoginMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.empire.msg.auto.cs.CSCSQuickLoginMsg.internal_static_com_empire_msg_auto_cs_CSQuickLoginMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg.class, com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg.Builder.class);
      }

      // Construct using com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.empire.msg.auto.cs.CSCSQuickLoginMsg.internal_static_com_empire_msg_auto_cs_CSQuickLoginMsg_descriptor;
      }

      public com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg getDefaultInstanceForType() {
        return com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg.getDefaultInstance();
      }

      public com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg build() {
        com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg buildPartial() {
        com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg result = new com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceType_ = deviceType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceId_ = deviceId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg) {
          return mergeFrom((com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg other) {
        if (other == com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg.getDefaultInstance()) return this;
        if (other.hasDeviceType()) {
          setDeviceType(other.getDeviceType());
        }
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000002;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.empire.msg.auto.cs.CSCSQuickLoginMsg.CSQuickLoginMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 deviceType = 1;
      private int deviceType_ ;
      /**
       * <code>optional int32 deviceType = 1;</code>
       */
      public boolean hasDeviceType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 deviceType = 1;</code>
       */
      public int getDeviceType() {
        return deviceType_;
      }
      /**
       * <code>optional int32 deviceType = 1;</code>
       */
      public Builder setDeviceType(int value) {
        bitField0_ |= 0x00000001;
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 deviceType = 1;</code>
       */
      public Builder clearDeviceType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceType_ = 0;
        onChanged();
        return this;
      }

      // optional string deviceId = 2;
      private java.lang.Object deviceId_ = "";
      /**
       * <code>optional string deviceId = 2;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string deviceId = 2;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deviceId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deviceId = 2;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceId = 2;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceId = 2;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.empire.msg.auto.cs.CSQuickLoginMsg)
    }

    static {
      defaultInstance = new CSQuickLoginMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.empire.msg.auto.cs.CSQuickLoginMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_empire_msg_auto_cs_CSQuickLoginMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_empire_msg_auto_cs_CSQuickLoginMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030CS.CSQuickLoginMsg.proto\022\026com.empire.m" +
      "sg.auto.cs\032\014struct.proto\"7\n\017CSQuickLogin" +
      "Msg\022\022\n\ndeviceType\030\001 \001(\005\022\020\n\010deviceId\030\002 \001(" +
      "\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_empire_msg_auto_cs_CSQuickLoginMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_empire_msg_auto_cs_CSQuickLoginMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_empire_msg_auto_cs_CSQuickLoginMsg_descriptor,
              new java.lang.String[] { "DeviceType", "DeviceId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.empire.msg.auto.Struct.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
