// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SC.SCPlayerInfoMsg.proto

package com.empire.msg.sc;

public final class SCSCPlayerInfoMsg {
  private SCSCPlayerInfoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SCPlayerInfoMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 sex = 1;
    /**
     * <code>optional int32 sex = 1;</code>
     */
    boolean hasSex();
    /**
     * <code>optional int32 sex = 1;</code>
     */
    int getSex();

    // optional int32 lvl = 2;
    /**
     * <code>optional int32 lvl = 2;</code>
     */
    boolean hasLvl();
    /**
     * <code>optional int32 lvl = 2;</code>
     */
    int getLvl();

    // optional int32 reputationLvl = 3;
    /**
     * <code>optional int32 reputationLvl = 3;</code>
     */
    boolean hasReputationLvl();
    /**
     * <code>optional int32 reputationLvl = 3;</code>
     */
    int getReputationLvl();

    // optional int32 govLvl = 4;
    /**
     * <code>optional int32 govLvl = 4;</code>
     */
    boolean hasGovLvl();
    /**
     * <code>optional int32 govLvl = 4;</code>
     */
    int getGovLvl();

    // optional int32 jwLvl = 5;
    /**
     * <code>optional int32 jwLvl = 5;</code>
     */
    boolean hasJwLvl();
    /**
     * <code>optional int32 jwLvl = 5;</code>
     */
    int getJwLvl();

    // optional int32 exp = 6;
    /**
     * <code>optional int32 exp = 6;</code>
     */
    boolean hasExp();
    /**
     * <code>optional int32 exp = 6;</code>
     */
    int getExp();

    // optional int64 diamond = 7;
    /**
     * <code>optional int64 diamond = 7;</code>
     */
    boolean hasDiamond();
    /**
     * <code>optional int64 diamond = 7;</code>
     */
    long getDiamond();

    // optional int64 gold = 8;
    /**
     * <code>optional int64 gold = 8;</code>
     */
    boolean hasGold();
    /**
     * <code>optional int64 gold = 8;</code>
     */
    long getGold();

    // optional int64 iron = 9;
    /**
     * <code>optional int64 iron = 9;</code>
     */
    boolean hasIron();
    /**
     * <code>optional int64 iron = 9;</code>
     */
    long getIron();

    // optional int64 tree = 10;
    /**
     * <code>optional int64 tree = 10;</code>
     */
    boolean hasTree();
    /**
     * <code>optional int64 tree = 10;</code>
     */
    long getTree();

    // optional int64 oil = 11;
    /**
     * <code>optional int64 oil = 11;</code>
     */
    boolean hasOil();
    /**
     * <code>optional int64 oil = 11;</code>
     */
    long getOil();

    // optional int64 magicStone = 12;
    /**
     * <code>optional int64 magicStone = 12;</code>
     */
    boolean hasMagicStone();
    /**
     * <code>optional int64 magicStone = 12;</code>
     */
    long getMagicStone();

    // repeated .com.empire.msg.BuildInfo buildInfos = 13;
    /**
     * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
     */
    java.util.List<com.empire.msg.Struct.BuildInfo> 
        getBuildInfosList();
    /**
     * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
     */
    com.empire.msg.Struct.BuildInfo getBuildInfos(int index);
    /**
     * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
     */
    int getBuildInfosCount();
    /**
     * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
     */
    java.util.List<? extends com.empire.msg.Struct.BuildInfoOrBuilder> 
        getBuildInfosOrBuilderList();
    /**
     * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
     */
    com.empire.msg.Struct.BuildInfoOrBuilder getBuildInfosOrBuilder(
        int index);

    // repeated .com.empire.msg.BoatInfo boatInfos = 14;
    /**
     * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
     */
    java.util.List<com.empire.msg.Struct.BoatInfo> 
        getBoatInfosList();
    /**
     * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
     */
    com.empire.msg.Struct.BoatInfo getBoatInfos(int index);
    /**
     * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
     */
    int getBoatInfosCount();
    /**
     * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
     */
    java.util.List<? extends com.empire.msg.Struct.BoatInfoOrBuilder> 
        getBoatInfosOrBuilderList();
    /**
     * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
     */
    com.empire.msg.Struct.BoatInfoOrBuilder getBoatInfosOrBuilder(
        int index);

    // optional int64 vipLvl = 15;
    /**
     * <code>optional int64 vipLvl = 15;</code>
     */
    boolean hasVipLvl();
    /**
     * <code>optional int64 vipLvl = 15;</code>
     */
    long getVipLvl();

    // optional string name = 16;
    /**
     * <code>optional string name = 16;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 16;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 16;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.empire.msg.sc.SCPlayerInfoMsg}
   */
  public static final class SCPlayerInfoMsg extends
      com.google.protobuf.GeneratedMessage
      implements SCPlayerInfoMsgOrBuilder {
    // Use SCPlayerInfoMsg.newBuilder() to construct.
    private SCPlayerInfoMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SCPlayerInfoMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SCPlayerInfoMsg defaultInstance;
    public static SCPlayerInfoMsg getDefaultInstance() {
      return defaultInstance;
    }

    public SCPlayerInfoMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SCPlayerInfoMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sex_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lvl_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              reputationLvl_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              govLvl_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              jwLvl_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              exp_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              diamond_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              gold_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              iron_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              tree_ = input.readInt64();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              oil_ = input.readInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              magicStone_ = input.readInt64();
              break;
            }
            case 106: {
              if (!((mutable_bitField0_ & 0x00001000) == 0x00001000)) {
                buildInfos_ = new java.util.ArrayList<com.empire.msg.Struct.BuildInfo>();
                mutable_bitField0_ |= 0x00001000;
              }
              buildInfos_.add(input.readMessage(com.empire.msg.Struct.BuildInfo.PARSER, extensionRegistry));
              break;
            }
            case 114: {
              if (!((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
                boatInfos_ = new java.util.ArrayList<com.empire.msg.Struct.BoatInfo>();
                mutable_bitField0_ |= 0x00002000;
              }
              boatInfos_.add(input.readMessage(com.empire.msg.Struct.BoatInfo.PARSER, extensionRegistry));
              break;
            }
            case 120: {
              bitField0_ |= 0x00001000;
              vipLvl_ = input.readInt64();
              break;
            }
            case 130: {
              bitField0_ |= 0x00002000;
              name_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00001000) == 0x00001000)) {
          buildInfos_ = java.util.Collections.unmodifiableList(buildInfos_);
        }
        if (((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
          boatInfos_ = java.util.Collections.unmodifiableList(boatInfos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.empire.msg.sc.SCSCPlayerInfoMsg.internal_static_com_empire_msg_sc_SCPlayerInfoMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.empire.msg.sc.SCSCPlayerInfoMsg.internal_static_com_empire_msg_sc_SCPlayerInfoMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg.class, com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<SCPlayerInfoMsg> PARSER =
        new com.google.protobuf.AbstractParser<SCPlayerInfoMsg>() {
      public SCPlayerInfoMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCPlayerInfoMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SCPlayerInfoMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 sex = 1;
    public static final int SEX_FIELD_NUMBER = 1;
    private int sex_;
    /**
     * <code>optional int32 sex = 1;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 sex = 1;</code>
     */
    public int getSex() {
      return sex_;
    }

    // optional int32 lvl = 2;
    public static final int LVL_FIELD_NUMBER = 2;
    private int lvl_;
    /**
     * <code>optional int32 lvl = 2;</code>
     */
    public boolean hasLvl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 lvl = 2;</code>
     */
    public int getLvl() {
      return lvl_;
    }

    // optional int32 reputationLvl = 3;
    public static final int REPUTATIONLVL_FIELD_NUMBER = 3;
    private int reputationLvl_;
    /**
     * <code>optional int32 reputationLvl = 3;</code>
     */
    public boolean hasReputationLvl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 reputationLvl = 3;</code>
     */
    public int getReputationLvl() {
      return reputationLvl_;
    }

    // optional int32 govLvl = 4;
    public static final int GOVLVL_FIELD_NUMBER = 4;
    private int govLvl_;
    /**
     * <code>optional int32 govLvl = 4;</code>
     */
    public boolean hasGovLvl() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 govLvl = 4;</code>
     */
    public int getGovLvl() {
      return govLvl_;
    }

    // optional int32 jwLvl = 5;
    public static final int JWLVL_FIELD_NUMBER = 5;
    private int jwLvl_;
    /**
     * <code>optional int32 jwLvl = 5;</code>
     */
    public boolean hasJwLvl() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 jwLvl = 5;</code>
     */
    public int getJwLvl() {
      return jwLvl_;
    }

    // optional int32 exp = 6;
    public static final int EXP_FIELD_NUMBER = 6;
    private int exp_;
    /**
     * <code>optional int32 exp = 6;</code>
     */
    public boolean hasExp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 exp = 6;</code>
     */
    public int getExp() {
      return exp_;
    }

    // optional int64 diamond = 7;
    public static final int DIAMOND_FIELD_NUMBER = 7;
    private long diamond_;
    /**
     * <code>optional int64 diamond = 7;</code>
     */
    public boolean hasDiamond() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 diamond = 7;</code>
     */
    public long getDiamond() {
      return diamond_;
    }

    // optional int64 gold = 8;
    public static final int GOLD_FIELD_NUMBER = 8;
    private long gold_;
    /**
     * <code>optional int64 gold = 8;</code>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 gold = 8;</code>
     */
    public long getGold() {
      return gold_;
    }

    // optional int64 iron = 9;
    public static final int IRON_FIELD_NUMBER = 9;
    private long iron_;
    /**
     * <code>optional int64 iron = 9;</code>
     */
    public boolean hasIron() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 iron = 9;</code>
     */
    public long getIron() {
      return iron_;
    }

    // optional int64 tree = 10;
    public static final int TREE_FIELD_NUMBER = 10;
    private long tree_;
    /**
     * <code>optional int64 tree = 10;</code>
     */
    public boolean hasTree() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int64 tree = 10;</code>
     */
    public long getTree() {
      return tree_;
    }

    // optional int64 oil = 11;
    public static final int OIL_FIELD_NUMBER = 11;
    private long oil_;
    /**
     * <code>optional int64 oil = 11;</code>
     */
    public boolean hasOil() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int64 oil = 11;</code>
     */
    public long getOil() {
      return oil_;
    }

    // optional int64 magicStone = 12;
    public static final int MAGICSTONE_FIELD_NUMBER = 12;
    private long magicStone_;
    /**
     * <code>optional int64 magicStone = 12;</code>
     */
    public boolean hasMagicStone() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int64 magicStone = 12;</code>
     */
    public long getMagicStone() {
      return magicStone_;
    }

    // repeated .com.empire.msg.BuildInfo buildInfos = 13;
    public static final int BUILDINFOS_FIELD_NUMBER = 13;
    private java.util.List<com.empire.msg.Struct.BuildInfo> buildInfos_;
    /**
     * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
     */
    public java.util.List<com.empire.msg.Struct.BuildInfo> getBuildInfosList() {
      return buildInfos_;
    }
    /**
     * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
     */
    public java.util.List<? extends com.empire.msg.Struct.BuildInfoOrBuilder> 
        getBuildInfosOrBuilderList() {
      return buildInfos_;
    }
    /**
     * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
     */
    public int getBuildInfosCount() {
      return buildInfos_.size();
    }
    /**
     * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
     */
    public com.empire.msg.Struct.BuildInfo getBuildInfos(int index) {
      return buildInfos_.get(index);
    }
    /**
     * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
     */
    public com.empire.msg.Struct.BuildInfoOrBuilder getBuildInfosOrBuilder(
        int index) {
      return buildInfos_.get(index);
    }

    // repeated .com.empire.msg.BoatInfo boatInfos = 14;
    public static final int BOATINFOS_FIELD_NUMBER = 14;
    private java.util.List<com.empire.msg.Struct.BoatInfo> boatInfos_;
    /**
     * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
     */
    public java.util.List<com.empire.msg.Struct.BoatInfo> getBoatInfosList() {
      return boatInfos_;
    }
    /**
     * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
     */
    public java.util.List<? extends com.empire.msg.Struct.BoatInfoOrBuilder> 
        getBoatInfosOrBuilderList() {
      return boatInfos_;
    }
    /**
     * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
     */
    public int getBoatInfosCount() {
      return boatInfos_.size();
    }
    /**
     * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
     */
    public com.empire.msg.Struct.BoatInfo getBoatInfos(int index) {
      return boatInfos_.get(index);
    }
    /**
     * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
     */
    public com.empire.msg.Struct.BoatInfoOrBuilder getBoatInfosOrBuilder(
        int index) {
      return boatInfos_.get(index);
    }

    // optional int64 vipLvl = 15;
    public static final int VIPLVL_FIELD_NUMBER = 15;
    private long vipLvl_;
    /**
     * <code>optional int64 vipLvl = 15;</code>
     */
    public boolean hasVipLvl() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int64 vipLvl = 15;</code>
     */
    public long getVipLvl() {
      return vipLvl_;
    }

    // optional string name = 16;
    public static final int NAME_FIELD_NUMBER = 16;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 16;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional string name = 16;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 16;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sex_ = 0;
      lvl_ = 0;
      reputationLvl_ = 0;
      govLvl_ = 0;
      jwLvl_ = 0;
      exp_ = 0;
      diamond_ = 0L;
      gold_ = 0L;
      iron_ = 0L;
      tree_ = 0L;
      oil_ = 0L;
      magicStone_ = 0L;
      buildInfos_ = java.util.Collections.emptyList();
      boatInfos_ = java.util.Collections.emptyList();
      vipLvl_ = 0L;
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, lvl_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, reputationLvl_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, govLvl_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, jwLvl_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, exp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, diamond_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, gold_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, iron_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, tree_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, oil_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt64(12, magicStone_);
      }
      for (int i = 0; i < buildInfos_.size(); i++) {
        output.writeMessage(13, buildInfos_.get(i));
      }
      for (int i = 0; i < boatInfos_.size(); i++) {
        output.writeMessage(14, boatInfos_.get(i));
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt64(15, vipLvl_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(16, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lvl_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, reputationLvl_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, govLvl_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, jwLvl_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, exp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, diamond_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, gold_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, iron_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, tree_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, oil_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, magicStone_);
      }
      for (int i = 0; i < buildInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, buildInfos_.get(i));
      }
      for (int i = 0; i < boatInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, boatInfos_.get(i));
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(15, vipLvl_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.empire.msg.sc.SCPlayerInfoMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.empire.msg.sc.SCSCPlayerInfoMsg.internal_static_com_empire_msg_sc_SCPlayerInfoMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.empire.msg.sc.SCSCPlayerInfoMsg.internal_static_com_empire_msg_sc_SCPlayerInfoMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg.class, com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg.Builder.class);
      }

      // Construct using com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBuildInfosFieldBuilder();
          getBoatInfosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        lvl_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        reputationLvl_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        govLvl_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        jwLvl_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        exp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        diamond_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        gold_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        iron_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        tree_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        oil_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        magicStone_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        if (buildInfosBuilder_ == null) {
          buildInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00001000);
        } else {
          buildInfosBuilder_.clear();
        }
        if (boatInfosBuilder_ == null) {
          boatInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00002000);
        } else {
          boatInfosBuilder_.clear();
        }
        vipLvl_ = 0L;
        bitField0_ = (bitField0_ & ~0x00004000);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.empire.msg.sc.SCSCPlayerInfoMsg.internal_static_com_empire_msg_sc_SCPlayerInfoMsg_descriptor;
      }

      public com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg getDefaultInstanceForType() {
        return com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg.getDefaultInstance();
      }

      public com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg build() {
        com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg buildPartial() {
        com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg result = new com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lvl_ = lvl_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.reputationLvl_ = reputationLvl_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.govLvl_ = govLvl_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.jwLvl_ = jwLvl_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.exp_ = exp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.diamond_ = diamond_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.gold_ = gold_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.iron_ = iron_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.tree_ = tree_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.oil_ = oil_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.magicStone_ = magicStone_;
        if (buildInfosBuilder_ == null) {
          if (((bitField0_ & 0x00001000) == 0x00001000)) {
            buildInfos_ = java.util.Collections.unmodifiableList(buildInfos_);
            bitField0_ = (bitField0_ & ~0x00001000);
          }
          result.buildInfos_ = buildInfos_;
        } else {
          result.buildInfos_ = buildInfosBuilder_.build();
        }
        if (boatInfosBuilder_ == null) {
          if (((bitField0_ & 0x00002000) == 0x00002000)) {
            boatInfos_ = java.util.Collections.unmodifiableList(boatInfos_);
            bitField0_ = (bitField0_ & ~0x00002000);
          }
          result.boatInfos_ = boatInfos_;
        } else {
          result.boatInfos_ = boatInfosBuilder_.build();
        }
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.vipLvl_ = vipLvl_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg) {
          return mergeFrom((com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg other) {
        if (other == com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg.getDefaultInstance()) return this;
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasLvl()) {
          setLvl(other.getLvl());
        }
        if (other.hasReputationLvl()) {
          setReputationLvl(other.getReputationLvl());
        }
        if (other.hasGovLvl()) {
          setGovLvl(other.getGovLvl());
        }
        if (other.hasJwLvl()) {
          setJwLvl(other.getJwLvl());
        }
        if (other.hasExp()) {
          setExp(other.getExp());
        }
        if (other.hasDiamond()) {
          setDiamond(other.getDiamond());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        if (other.hasIron()) {
          setIron(other.getIron());
        }
        if (other.hasTree()) {
          setTree(other.getTree());
        }
        if (other.hasOil()) {
          setOil(other.getOil());
        }
        if (other.hasMagicStone()) {
          setMagicStone(other.getMagicStone());
        }
        if (buildInfosBuilder_ == null) {
          if (!other.buildInfos_.isEmpty()) {
            if (buildInfos_.isEmpty()) {
              buildInfos_ = other.buildInfos_;
              bitField0_ = (bitField0_ & ~0x00001000);
            } else {
              ensureBuildInfosIsMutable();
              buildInfos_.addAll(other.buildInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.buildInfos_.isEmpty()) {
            if (buildInfosBuilder_.isEmpty()) {
              buildInfosBuilder_.dispose();
              buildInfosBuilder_ = null;
              buildInfos_ = other.buildInfos_;
              bitField0_ = (bitField0_ & ~0x00001000);
              buildInfosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBuildInfosFieldBuilder() : null;
            } else {
              buildInfosBuilder_.addAllMessages(other.buildInfos_);
            }
          }
        }
        if (boatInfosBuilder_ == null) {
          if (!other.boatInfos_.isEmpty()) {
            if (boatInfos_.isEmpty()) {
              boatInfos_ = other.boatInfos_;
              bitField0_ = (bitField0_ & ~0x00002000);
            } else {
              ensureBoatInfosIsMutable();
              boatInfos_.addAll(other.boatInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.boatInfos_.isEmpty()) {
            if (boatInfosBuilder_.isEmpty()) {
              boatInfosBuilder_.dispose();
              boatInfosBuilder_ = null;
              boatInfos_ = other.boatInfos_;
              bitField0_ = (bitField0_ & ~0x00002000);
              boatInfosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBoatInfosFieldBuilder() : null;
            } else {
              boatInfosBuilder_.addAllMessages(other.boatInfos_);
            }
          }
        }
        if (other.hasVipLvl()) {
          setVipLvl(other.getVipLvl());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00008000;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.empire.msg.sc.SCSCPlayerInfoMsg.SCPlayerInfoMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 sex = 1;
      private int sex_ ;
      /**
       * <code>optional int32 sex = 1;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 sex = 1;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>optional int32 sex = 1;</code>
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00000001;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sex = 1;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sex_ = 0;
        onChanged();
        return this;
      }

      // optional int32 lvl = 2;
      private int lvl_ ;
      /**
       * <code>optional int32 lvl = 2;</code>
       */
      public boolean hasLvl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 lvl = 2;</code>
       */
      public int getLvl() {
        return lvl_;
      }
      /**
       * <code>optional int32 lvl = 2;</code>
       */
      public Builder setLvl(int value) {
        bitField0_ |= 0x00000002;
        lvl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 lvl = 2;</code>
       */
      public Builder clearLvl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lvl_ = 0;
        onChanged();
        return this;
      }

      // optional int32 reputationLvl = 3;
      private int reputationLvl_ ;
      /**
       * <code>optional int32 reputationLvl = 3;</code>
       */
      public boolean hasReputationLvl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 reputationLvl = 3;</code>
       */
      public int getReputationLvl() {
        return reputationLvl_;
      }
      /**
       * <code>optional int32 reputationLvl = 3;</code>
       */
      public Builder setReputationLvl(int value) {
        bitField0_ |= 0x00000004;
        reputationLvl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 reputationLvl = 3;</code>
       */
      public Builder clearReputationLvl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        reputationLvl_ = 0;
        onChanged();
        return this;
      }

      // optional int32 govLvl = 4;
      private int govLvl_ ;
      /**
       * <code>optional int32 govLvl = 4;</code>
       */
      public boolean hasGovLvl() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 govLvl = 4;</code>
       */
      public int getGovLvl() {
        return govLvl_;
      }
      /**
       * <code>optional int32 govLvl = 4;</code>
       */
      public Builder setGovLvl(int value) {
        bitField0_ |= 0x00000008;
        govLvl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 govLvl = 4;</code>
       */
      public Builder clearGovLvl() {
        bitField0_ = (bitField0_ & ~0x00000008);
        govLvl_ = 0;
        onChanged();
        return this;
      }

      // optional int32 jwLvl = 5;
      private int jwLvl_ ;
      /**
       * <code>optional int32 jwLvl = 5;</code>
       */
      public boolean hasJwLvl() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 jwLvl = 5;</code>
       */
      public int getJwLvl() {
        return jwLvl_;
      }
      /**
       * <code>optional int32 jwLvl = 5;</code>
       */
      public Builder setJwLvl(int value) {
        bitField0_ |= 0x00000010;
        jwLvl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 jwLvl = 5;</code>
       */
      public Builder clearJwLvl() {
        bitField0_ = (bitField0_ & ~0x00000010);
        jwLvl_ = 0;
        onChanged();
        return this;
      }

      // optional int32 exp = 6;
      private int exp_ ;
      /**
       * <code>optional int32 exp = 6;</code>
       */
      public boolean hasExp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 exp = 6;</code>
       */
      public int getExp() {
        return exp_;
      }
      /**
       * <code>optional int32 exp = 6;</code>
       */
      public Builder setExp(int value) {
        bitField0_ |= 0x00000020;
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 exp = 6;</code>
       */
      public Builder clearExp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        exp_ = 0;
        onChanged();
        return this;
      }

      // optional int64 diamond = 7;
      private long diamond_ ;
      /**
       * <code>optional int64 diamond = 7;</code>
       */
      public boolean hasDiamond() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 diamond = 7;</code>
       */
      public long getDiamond() {
        return diamond_;
      }
      /**
       * <code>optional int64 diamond = 7;</code>
       */
      public Builder setDiamond(long value) {
        bitField0_ |= 0x00000040;
        diamond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 diamond = 7;</code>
       */
      public Builder clearDiamond() {
        bitField0_ = (bitField0_ & ~0x00000040);
        diamond_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 gold = 8;
      private long gold_ ;
      /**
       * <code>optional int64 gold = 8;</code>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 gold = 8;</code>
       */
      public long getGold() {
        return gold_;
      }
      /**
       * <code>optional int64 gold = 8;</code>
       */
      public Builder setGold(long value) {
        bitField0_ |= 0x00000080;
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 gold = 8;</code>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000080);
        gold_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 iron = 9;
      private long iron_ ;
      /**
       * <code>optional int64 iron = 9;</code>
       */
      public boolean hasIron() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 iron = 9;</code>
       */
      public long getIron() {
        return iron_;
      }
      /**
       * <code>optional int64 iron = 9;</code>
       */
      public Builder setIron(long value) {
        bitField0_ |= 0x00000100;
        iron_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 iron = 9;</code>
       */
      public Builder clearIron() {
        bitField0_ = (bitField0_ & ~0x00000100);
        iron_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 tree = 10;
      private long tree_ ;
      /**
       * <code>optional int64 tree = 10;</code>
       */
      public boolean hasTree() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int64 tree = 10;</code>
       */
      public long getTree() {
        return tree_;
      }
      /**
       * <code>optional int64 tree = 10;</code>
       */
      public Builder setTree(long value) {
        bitField0_ |= 0x00000200;
        tree_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 tree = 10;</code>
       */
      public Builder clearTree() {
        bitField0_ = (bitField0_ & ~0x00000200);
        tree_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 oil = 11;
      private long oil_ ;
      /**
       * <code>optional int64 oil = 11;</code>
       */
      public boolean hasOil() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int64 oil = 11;</code>
       */
      public long getOil() {
        return oil_;
      }
      /**
       * <code>optional int64 oil = 11;</code>
       */
      public Builder setOil(long value) {
        bitField0_ |= 0x00000400;
        oil_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 oil = 11;</code>
       */
      public Builder clearOil() {
        bitField0_ = (bitField0_ & ~0x00000400);
        oil_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 magicStone = 12;
      private long magicStone_ ;
      /**
       * <code>optional int64 magicStone = 12;</code>
       */
      public boolean hasMagicStone() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int64 magicStone = 12;</code>
       */
      public long getMagicStone() {
        return magicStone_;
      }
      /**
       * <code>optional int64 magicStone = 12;</code>
       */
      public Builder setMagicStone(long value) {
        bitField0_ |= 0x00000800;
        magicStone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 magicStone = 12;</code>
       */
      public Builder clearMagicStone() {
        bitField0_ = (bitField0_ & ~0x00000800);
        magicStone_ = 0L;
        onChanged();
        return this;
      }

      // repeated .com.empire.msg.BuildInfo buildInfos = 13;
      private java.util.List<com.empire.msg.Struct.BuildInfo> buildInfos_ =
        java.util.Collections.emptyList();
      private void ensureBuildInfosIsMutable() {
        if (!((bitField0_ & 0x00001000) == 0x00001000)) {
          buildInfos_ = new java.util.ArrayList<com.empire.msg.Struct.BuildInfo>(buildInfos_);
          bitField0_ |= 0x00001000;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.empire.msg.Struct.BuildInfo, com.empire.msg.Struct.BuildInfo.Builder, com.empire.msg.Struct.BuildInfoOrBuilder> buildInfosBuilder_;

      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public java.util.List<com.empire.msg.Struct.BuildInfo> getBuildInfosList() {
        if (buildInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(buildInfos_);
        } else {
          return buildInfosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public int getBuildInfosCount() {
        if (buildInfosBuilder_ == null) {
          return buildInfos_.size();
        } else {
          return buildInfosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public com.empire.msg.Struct.BuildInfo getBuildInfos(int index) {
        if (buildInfosBuilder_ == null) {
          return buildInfos_.get(index);
        } else {
          return buildInfosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public Builder setBuildInfos(
          int index, com.empire.msg.Struct.BuildInfo value) {
        if (buildInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuildInfosIsMutable();
          buildInfos_.set(index, value);
          onChanged();
        } else {
          buildInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public Builder setBuildInfos(
          int index, com.empire.msg.Struct.BuildInfo.Builder builderForValue) {
        if (buildInfosBuilder_ == null) {
          ensureBuildInfosIsMutable();
          buildInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          buildInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public Builder addBuildInfos(com.empire.msg.Struct.BuildInfo value) {
        if (buildInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuildInfosIsMutable();
          buildInfos_.add(value);
          onChanged();
        } else {
          buildInfosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public Builder addBuildInfos(
          int index, com.empire.msg.Struct.BuildInfo value) {
        if (buildInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuildInfosIsMutable();
          buildInfos_.add(index, value);
          onChanged();
        } else {
          buildInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public Builder addBuildInfos(
          com.empire.msg.Struct.BuildInfo.Builder builderForValue) {
        if (buildInfosBuilder_ == null) {
          ensureBuildInfosIsMutable();
          buildInfos_.add(builderForValue.build());
          onChanged();
        } else {
          buildInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public Builder addBuildInfos(
          int index, com.empire.msg.Struct.BuildInfo.Builder builderForValue) {
        if (buildInfosBuilder_ == null) {
          ensureBuildInfosIsMutable();
          buildInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          buildInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public Builder addAllBuildInfos(
          java.lang.Iterable<? extends com.empire.msg.Struct.BuildInfo> values) {
        if (buildInfosBuilder_ == null) {
          ensureBuildInfosIsMutable();
          super.addAll(values, buildInfos_);
          onChanged();
        } else {
          buildInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public Builder clearBuildInfos() {
        if (buildInfosBuilder_ == null) {
          buildInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00001000);
          onChanged();
        } else {
          buildInfosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public Builder removeBuildInfos(int index) {
        if (buildInfosBuilder_ == null) {
          ensureBuildInfosIsMutable();
          buildInfos_.remove(index);
          onChanged();
        } else {
          buildInfosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public com.empire.msg.Struct.BuildInfo.Builder getBuildInfosBuilder(
          int index) {
        return getBuildInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public com.empire.msg.Struct.BuildInfoOrBuilder getBuildInfosOrBuilder(
          int index) {
        if (buildInfosBuilder_ == null) {
          return buildInfos_.get(index);  } else {
          return buildInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public java.util.List<? extends com.empire.msg.Struct.BuildInfoOrBuilder> 
           getBuildInfosOrBuilderList() {
        if (buildInfosBuilder_ != null) {
          return buildInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(buildInfos_);
        }
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public com.empire.msg.Struct.BuildInfo.Builder addBuildInfosBuilder() {
        return getBuildInfosFieldBuilder().addBuilder(
            com.empire.msg.Struct.BuildInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public com.empire.msg.Struct.BuildInfo.Builder addBuildInfosBuilder(
          int index) {
        return getBuildInfosFieldBuilder().addBuilder(
            index, com.empire.msg.Struct.BuildInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.empire.msg.BuildInfo buildInfos = 13;</code>
       */
      public java.util.List<com.empire.msg.Struct.BuildInfo.Builder> 
           getBuildInfosBuilderList() {
        return getBuildInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.empire.msg.Struct.BuildInfo, com.empire.msg.Struct.BuildInfo.Builder, com.empire.msg.Struct.BuildInfoOrBuilder> 
          getBuildInfosFieldBuilder() {
        if (buildInfosBuilder_ == null) {
          buildInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.empire.msg.Struct.BuildInfo, com.empire.msg.Struct.BuildInfo.Builder, com.empire.msg.Struct.BuildInfoOrBuilder>(
                  buildInfos_,
                  ((bitField0_ & 0x00001000) == 0x00001000),
                  getParentForChildren(),
                  isClean());
          buildInfos_ = null;
        }
        return buildInfosBuilder_;
      }

      // repeated .com.empire.msg.BoatInfo boatInfos = 14;
      private java.util.List<com.empire.msg.Struct.BoatInfo> boatInfos_ =
        java.util.Collections.emptyList();
      private void ensureBoatInfosIsMutable() {
        if (!((bitField0_ & 0x00002000) == 0x00002000)) {
          boatInfos_ = new java.util.ArrayList<com.empire.msg.Struct.BoatInfo>(boatInfos_);
          bitField0_ |= 0x00002000;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.empire.msg.Struct.BoatInfo, com.empire.msg.Struct.BoatInfo.Builder, com.empire.msg.Struct.BoatInfoOrBuilder> boatInfosBuilder_;

      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public java.util.List<com.empire.msg.Struct.BoatInfo> getBoatInfosList() {
        if (boatInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(boatInfos_);
        } else {
          return boatInfosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public int getBoatInfosCount() {
        if (boatInfosBuilder_ == null) {
          return boatInfos_.size();
        } else {
          return boatInfosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public com.empire.msg.Struct.BoatInfo getBoatInfos(int index) {
        if (boatInfosBuilder_ == null) {
          return boatInfos_.get(index);
        } else {
          return boatInfosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public Builder setBoatInfos(
          int index, com.empire.msg.Struct.BoatInfo value) {
        if (boatInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBoatInfosIsMutable();
          boatInfos_.set(index, value);
          onChanged();
        } else {
          boatInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public Builder setBoatInfos(
          int index, com.empire.msg.Struct.BoatInfo.Builder builderForValue) {
        if (boatInfosBuilder_ == null) {
          ensureBoatInfosIsMutable();
          boatInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          boatInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public Builder addBoatInfos(com.empire.msg.Struct.BoatInfo value) {
        if (boatInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBoatInfosIsMutable();
          boatInfos_.add(value);
          onChanged();
        } else {
          boatInfosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public Builder addBoatInfos(
          int index, com.empire.msg.Struct.BoatInfo value) {
        if (boatInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBoatInfosIsMutable();
          boatInfos_.add(index, value);
          onChanged();
        } else {
          boatInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public Builder addBoatInfos(
          com.empire.msg.Struct.BoatInfo.Builder builderForValue) {
        if (boatInfosBuilder_ == null) {
          ensureBoatInfosIsMutable();
          boatInfos_.add(builderForValue.build());
          onChanged();
        } else {
          boatInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public Builder addBoatInfos(
          int index, com.empire.msg.Struct.BoatInfo.Builder builderForValue) {
        if (boatInfosBuilder_ == null) {
          ensureBoatInfosIsMutable();
          boatInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          boatInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public Builder addAllBoatInfos(
          java.lang.Iterable<? extends com.empire.msg.Struct.BoatInfo> values) {
        if (boatInfosBuilder_ == null) {
          ensureBoatInfosIsMutable();
          super.addAll(values, boatInfos_);
          onChanged();
        } else {
          boatInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public Builder clearBoatInfos() {
        if (boatInfosBuilder_ == null) {
          boatInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00002000);
          onChanged();
        } else {
          boatInfosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public Builder removeBoatInfos(int index) {
        if (boatInfosBuilder_ == null) {
          ensureBoatInfosIsMutable();
          boatInfos_.remove(index);
          onChanged();
        } else {
          boatInfosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public com.empire.msg.Struct.BoatInfo.Builder getBoatInfosBuilder(
          int index) {
        return getBoatInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public com.empire.msg.Struct.BoatInfoOrBuilder getBoatInfosOrBuilder(
          int index) {
        if (boatInfosBuilder_ == null) {
          return boatInfos_.get(index);  } else {
          return boatInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public java.util.List<? extends com.empire.msg.Struct.BoatInfoOrBuilder> 
           getBoatInfosOrBuilderList() {
        if (boatInfosBuilder_ != null) {
          return boatInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(boatInfos_);
        }
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public com.empire.msg.Struct.BoatInfo.Builder addBoatInfosBuilder() {
        return getBoatInfosFieldBuilder().addBuilder(
            com.empire.msg.Struct.BoatInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public com.empire.msg.Struct.BoatInfo.Builder addBoatInfosBuilder(
          int index) {
        return getBoatInfosFieldBuilder().addBuilder(
            index, com.empire.msg.Struct.BoatInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.empire.msg.BoatInfo boatInfos = 14;</code>
       */
      public java.util.List<com.empire.msg.Struct.BoatInfo.Builder> 
           getBoatInfosBuilderList() {
        return getBoatInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.empire.msg.Struct.BoatInfo, com.empire.msg.Struct.BoatInfo.Builder, com.empire.msg.Struct.BoatInfoOrBuilder> 
          getBoatInfosFieldBuilder() {
        if (boatInfosBuilder_ == null) {
          boatInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.empire.msg.Struct.BoatInfo, com.empire.msg.Struct.BoatInfo.Builder, com.empire.msg.Struct.BoatInfoOrBuilder>(
                  boatInfos_,
                  ((bitField0_ & 0x00002000) == 0x00002000),
                  getParentForChildren(),
                  isClean());
          boatInfos_ = null;
        }
        return boatInfosBuilder_;
      }

      // optional int64 vipLvl = 15;
      private long vipLvl_ ;
      /**
       * <code>optional int64 vipLvl = 15;</code>
       */
      public boolean hasVipLvl() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional int64 vipLvl = 15;</code>
       */
      public long getVipLvl() {
        return vipLvl_;
      }
      /**
       * <code>optional int64 vipLvl = 15;</code>
       */
      public Builder setVipLvl(long value) {
        bitField0_ |= 0x00004000;
        vipLvl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 vipLvl = 15;</code>
       */
      public Builder clearVipLvl() {
        bitField0_ = (bitField0_ & ~0x00004000);
        vipLvl_ = 0L;
        onChanged();
        return this;
      }

      // optional string name = 16;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 16;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional string name = 16;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 16;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 16;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 16;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00008000);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 16;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.empire.msg.sc.SCPlayerInfoMsg)
    }

    static {
      defaultInstance = new SCPlayerInfoMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.empire.msg.sc.SCPlayerInfoMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_empire_msg_sc_SCPlayerInfoMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_empire_msg_sc_SCPlayerInfoMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030SC.SCPlayerInfoMsg.proto\022\021com.empire.m" +
      "sg.sc\032\014struct.proto\"\304\002\n\017SCPlayerInfoMsg\022" +
      "\013\n\003sex\030\001 \001(\005\022\013\n\003lvl\030\002 \001(\005\022\025\n\rreputationL" +
      "vl\030\003 \001(\005\022\016\n\006govLvl\030\004 \001(\005\022\r\n\005jwLvl\030\005 \001(\005\022" +
      "\013\n\003exp\030\006 \001(\005\022\017\n\007diamond\030\007 \001(\003\022\014\n\004gold\030\010 " +
      "\001(\003\022\014\n\004iron\030\t \001(\003\022\014\n\004tree\030\n \001(\003\022\013\n\003oil\030\013" +
      " \001(\003\022\022\n\nmagicStone\030\014 \001(\003\022-\n\nbuildInfos\030\r" +
      " \003(\0132\031.com.empire.msg.BuildInfo\022+\n\tboatI" +
      "nfos\030\016 \003(\0132\030.com.empire.msg.BoatInfo\022\016\n\006" +
      "vipLvl\030\017 \001(\003\022\014\n\004name\030\020 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_empire_msg_sc_SCPlayerInfoMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_empire_msg_sc_SCPlayerInfoMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_empire_msg_sc_SCPlayerInfoMsg_descriptor,
              new java.lang.String[] { "Sex", "Lvl", "ReputationLvl", "GovLvl", "JwLvl", "Exp", "Diamond", "Gold", "Iron", "Tree", "Oil", "MagicStone", "BuildInfos", "BoatInfos", "VipLvl", "Name", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.empire.msg.Struct.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
