/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef item.cs_CONSTANTS_H
#define item.cs_CONSTANTS_H

#include "item.cs_types.h"



class item.csConstants {
 public:
  item.csConstants();

};

extern const item.csConstants g_item.cs_constants;



#endif
