// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boat.sc.proto

#ifndef PROTOBUF_boat_2esc_2eproto__INCLUDED
#define PROTOBUF_boat_2esc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "struct.pb.h"
// @@protoc_insertion_point(includes)

namespace com {
namespace empire {
namespace msg {
namespace sc {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_boat_2esc_2eproto();
void protobuf_AssignDesc_boat_2esc_2eproto();
void protobuf_ShutdownFile_boat_2esc_2eproto();

class SCBoatExtraBPropertyMsg;

// ===================================================================

class SCBoatExtraBPropertyMsg : public ::google::protobuf::Message {
 public:
  SCBoatExtraBPropertyMsg();
  virtual ~SCBoatExtraBPropertyMsg();

  SCBoatExtraBPropertyMsg(const SCBoatExtraBPropertyMsg& from);

  inline SCBoatExtraBPropertyMsg& operator=(const SCBoatExtraBPropertyMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SCBoatExtraBPropertyMsg& default_instance();

  void Swap(SCBoatExtraBPropertyMsg* other);

  // implements Message ----------------------------------------------

  SCBoatExtraBPropertyMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SCBoatExtraBPropertyMsg& from);
  void MergeFrom(const SCBoatExtraBPropertyMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .com.empire.msg.BattlePropertyType type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::com::empire::msg::BattlePropertyType type() const;
  inline void set_type(::com::empire::msg::BattlePropertyType value);

  // optional string value = 2;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 2;
  inline const ::std::string& value() const;
  inline void set_value(const ::std::string& value);
  inline void set_value(const char* value);
  inline void set_value(const char* value, size_t size);
  inline ::std::string* mutable_value();
  inline ::std::string* release_value();
  inline void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:com.empire.msg.sc.SCBoatExtraBPropertyMsg)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_value();
  inline void clear_has_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* value_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_boat_2esc_2eproto();
  friend void protobuf_AssignDesc_boat_2esc_2eproto();
  friend void protobuf_ShutdownFile_boat_2esc_2eproto();

  void InitAsDefaultInstance();
  static SCBoatExtraBPropertyMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// SCBoatExtraBPropertyMsg

// optional .com.empire.msg.BattlePropertyType type = 1;
inline bool SCBoatExtraBPropertyMsg::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SCBoatExtraBPropertyMsg::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SCBoatExtraBPropertyMsg::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SCBoatExtraBPropertyMsg::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::com::empire::msg::BattlePropertyType SCBoatExtraBPropertyMsg::type() const {
  return static_cast< ::com::empire::msg::BattlePropertyType >(type_);
}
inline void SCBoatExtraBPropertyMsg::set_type(::com::empire::msg::BattlePropertyType value) {
  assert(::com::empire::msg::BattlePropertyType_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional string value = 2;
inline bool SCBoatExtraBPropertyMsg::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SCBoatExtraBPropertyMsg::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SCBoatExtraBPropertyMsg::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SCBoatExtraBPropertyMsg::clear_value() {
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    value_->clear();
  }
  clear_has_value();
}
inline const ::std::string& SCBoatExtraBPropertyMsg::value() const {
  return *value_;
}
inline void SCBoatExtraBPropertyMsg::set_value(const ::std::string& value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
inline void SCBoatExtraBPropertyMsg::set_value(const char* value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
inline void SCBoatExtraBPropertyMsg::set_value(const char* value, size_t size) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SCBoatExtraBPropertyMsg::mutable_value() {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  return value_;
}
inline ::std::string* SCBoatExtraBPropertyMsg::release_value() {
  clear_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = value_;
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void SCBoatExtraBPropertyMsg::set_allocated_value(::std::string* value) {
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    delete value_;
  }
  if (value) {
    set_has_value();
    value_ = value;
  } else {
    clear_has_value();
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace sc
}  // namespace msg
}  // namespace empire
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_boat_2esc_2eproto__INCLUDED
