// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boat.cs.proto

#ifndef PROTOBUF_boat_2ecs_2eproto__INCLUDED
#define PROTOBUF_boat_2ecs_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace empire {
namespace msg {
namespace cs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_boat_2ecs_2eproto();
void protobuf_AssignDesc_boat_2ecs_2eproto();
void protobuf_ShutdownFile_boat_2ecs_2eproto();

class CSQueryBoatInfoMsg;

// ===================================================================

class CSQueryBoatInfoMsg : public ::google::protobuf::Message {
 public:
  CSQueryBoatInfoMsg();
  virtual ~CSQueryBoatInfoMsg();

  CSQueryBoatInfoMsg(const CSQueryBoatInfoMsg& from);

  inline CSQueryBoatInfoMsg& operator=(const CSQueryBoatInfoMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSQueryBoatInfoMsg& default_instance();

  void Swap(CSQueryBoatInfoMsg* other);

  // implements Message ----------------------------------------------

  CSQueryBoatInfoMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSQueryBoatInfoMsg& from);
  void MergeFrom(const CSQueryBoatInfoMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string boatId = 1;
  inline bool has_boatid() const;
  inline void clear_boatid();
  static const int kBoatIdFieldNumber = 1;
  inline const ::std::string& boatid() const;
  inline void set_boatid(const ::std::string& value);
  inline void set_boatid(const char* value);
  inline void set_boatid(const char* value, size_t size);
  inline ::std::string* mutable_boatid();
  inline ::std::string* release_boatid();
  inline void set_allocated_boatid(::std::string* boatid);

  // @@protoc_insertion_point(class_scope:com.empire.msg.cs.CSQueryBoatInfoMsg)
 private:
  inline void set_has_boatid();
  inline void clear_has_boatid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* boatid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_boat_2ecs_2eproto();
  friend void protobuf_AssignDesc_boat_2ecs_2eproto();
  friend void protobuf_ShutdownFile_boat_2ecs_2eproto();

  void InitAsDefaultInstance();
  static CSQueryBoatInfoMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// CSQueryBoatInfoMsg

// optional string boatId = 1;
inline bool CSQueryBoatInfoMsg::has_boatid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSQueryBoatInfoMsg::set_has_boatid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CSQueryBoatInfoMsg::clear_has_boatid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CSQueryBoatInfoMsg::clear_boatid() {
  if (boatid_ != &::google::protobuf::internal::kEmptyString) {
    boatid_->clear();
  }
  clear_has_boatid();
}
inline const ::std::string& CSQueryBoatInfoMsg::boatid() const {
  return *boatid_;
}
inline void CSQueryBoatInfoMsg::set_boatid(const ::std::string& value) {
  set_has_boatid();
  if (boatid_ == &::google::protobuf::internal::kEmptyString) {
    boatid_ = new ::std::string;
  }
  boatid_->assign(value);
}
inline void CSQueryBoatInfoMsg::set_boatid(const char* value) {
  set_has_boatid();
  if (boatid_ == &::google::protobuf::internal::kEmptyString) {
    boatid_ = new ::std::string;
  }
  boatid_->assign(value);
}
inline void CSQueryBoatInfoMsg::set_boatid(const char* value, size_t size) {
  set_has_boatid();
  if (boatid_ == &::google::protobuf::internal::kEmptyString) {
    boatid_ = new ::std::string;
  }
  boatid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CSQueryBoatInfoMsg::mutable_boatid() {
  set_has_boatid();
  if (boatid_ == &::google::protobuf::internal::kEmptyString) {
    boatid_ = new ::std::string;
  }
  return boatid_;
}
inline ::std::string* CSQueryBoatInfoMsg::release_boatid() {
  clear_has_boatid();
  if (boatid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = boatid_;
    boatid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CSQueryBoatInfoMsg::set_allocated_boatid(::std::string* boatid) {
  if (boatid_ != &::google::protobuf::internal::kEmptyString) {
    delete boatid_;
  }
  if (boatid) {
    set_has_boatid();
    boatid_ = boatid;
  } else {
    clear_has_boatid();
    boatid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace cs
}  // namespace msg
}  // namespace empire
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_boat_2ecs_2eproto__INCLUDED
