// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boat.sc.proto

package com.empire.msg.auto.sc;

public final class BoatSc {
  private BoatSc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SCBoatExtraBPropertyMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.empire.msg.auto.BattlePropertyType type = 1;
    /**
     * <code>optional .com.empire.msg.auto.BattlePropertyType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .com.empire.msg.auto.BattlePropertyType type = 1;</code>
     */
    com.empire.msg.auto.Struct.BattlePropertyType getType();

    // optional string value = 2;
    /**
     * <code>optional string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>optional string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code com.empire.msg.auto.sc.SCBoatExtraBPropertyMsg}
   */
  public static final class SCBoatExtraBPropertyMsg extends
      com.google.protobuf.GeneratedMessage
      implements SCBoatExtraBPropertyMsgOrBuilder {
    // Use SCBoatExtraBPropertyMsg.newBuilder() to construct.
    private SCBoatExtraBPropertyMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SCBoatExtraBPropertyMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SCBoatExtraBPropertyMsg defaultInstance;
    public static SCBoatExtraBPropertyMsg getDefaultInstance() {
      return defaultInstance;
    }

    public SCBoatExtraBPropertyMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SCBoatExtraBPropertyMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.empire.msg.auto.Struct.BattlePropertyType value = com.empire.msg.auto.Struct.BattlePropertyType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.empire.msg.auto.sc.BoatSc.internal_static_com_empire_msg_auto_sc_SCBoatExtraBPropertyMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.empire.msg.auto.sc.BoatSc.internal_static_com_empire_msg_auto_sc_SCBoatExtraBPropertyMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg.class, com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<SCBoatExtraBPropertyMsg> PARSER =
        new com.google.protobuf.AbstractParser<SCBoatExtraBPropertyMsg>() {
      public SCBoatExtraBPropertyMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCBoatExtraBPropertyMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SCBoatExtraBPropertyMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.empire.msg.auto.BattlePropertyType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.empire.msg.auto.Struct.BattlePropertyType type_;
    /**
     * <code>optional .com.empire.msg.auto.BattlePropertyType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.empire.msg.auto.BattlePropertyType type = 1;</code>
     */
    public com.empire.msg.auto.Struct.BattlePropertyType getType() {
      return type_;
    }

    // optional string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    /**
     * <code>optional string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = com.empire.msg.auto.Struct.BattlePropertyType.TEST;
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.empire.msg.auto.sc.SCBoatExtraBPropertyMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.empire.msg.auto.sc.BoatSc.internal_static_com_empire_msg_auto_sc_SCBoatExtraBPropertyMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.empire.msg.auto.sc.BoatSc.internal_static_com_empire_msg_auto_sc_SCBoatExtraBPropertyMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg.class, com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg.Builder.class);
      }

      // Construct using com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.empire.msg.auto.Struct.BattlePropertyType.TEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.empire.msg.auto.sc.BoatSc.internal_static_com_empire_msg_auto_sc_SCBoatExtraBPropertyMsg_descriptor;
      }

      public com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg getDefaultInstanceForType() {
        return com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg.getDefaultInstance();
      }

      public com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg build() {
        com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg buildPartial() {
        com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg result = new com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg) {
          return mergeFrom((com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg other) {
        if (other == com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.empire.msg.auto.sc.BoatSc.SCBoatExtraBPropertyMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.empire.msg.auto.BattlePropertyType type = 1;
      private com.empire.msg.auto.Struct.BattlePropertyType type_ = com.empire.msg.auto.Struct.BattlePropertyType.TEST;
      /**
       * <code>optional .com.empire.msg.auto.BattlePropertyType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.empire.msg.auto.BattlePropertyType type = 1;</code>
       */
      public com.empire.msg.auto.Struct.BattlePropertyType getType() {
        return type_;
      }
      /**
       * <code>optional .com.empire.msg.auto.BattlePropertyType type = 1;</code>
       */
      public Builder setType(com.empire.msg.auto.Struct.BattlePropertyType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.empire.msg.auto.BattlePropertyType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.empire.msg.auto.Struct.BattlePropertyType.TEST;
        onChanged();
        return this;
      }

      // optional string value = 2;
      private java.lang.Object value_ = "";
      /**
       * <code>optional string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.empire.msg.auto.sc.SCBoatExtraBPropertyMsg)
    }

    static {
      defaultInstance = new SCBoatExtraBPropertyMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.empire.msg.auto.sc.SCBoatExtraBPropertyMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_empire_msg_auto_sc_SCBoatExtraBPropertyMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_empire_msg_auto_sc_SCBoatExtraBPropertyMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rboat.sc.proto\022\026com.empire.msg.auto.sc\032" +
      "\014struct.proto\"_\n\027SCBoatExtraBPropertyMsg" +
      "\0225\n\004type\030\001 \001(\0162\'.com.empire.msg.auto.Bat" +
      "tlePropertyType\022\r\n\005value\030\002 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_empire_msg_auto_sc_SCBoatExtraBPropertyMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_empire_msg_auto_sc_SCBoatExtraBPropertyMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_empire_msg_auto_sc_SCBoatExtraBPropertyMsg_descriptor,
              new java.lang.String[] { "Type", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.empire.msg.auto.Struct.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
