// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SC.SCServerListMsg.proto

package com.empire.msg.auto.sc;

public final class SCSCServerListMsg {
  private SCSCServerListMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SCServerListMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 id = 1;
    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    // repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;
    /**
     * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
     */
    java.util.List<com.empire.msg.auto.Struct.ServerInfo> 
        getServerInfosList();
    /**
     * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
     */
    com.empire.msg.auto.Struct.ServerInfo getServerInfos(int index);
    /**
     * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
     */
    int getServerInfosCount();
    /**
     * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
     */
    java.util.List<? extends com.empire.msg.auto.Struct.ServerInfoOrBuilder> 
        getServerInfosOrBuilderList();
    /**
     * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
     */
    com.empire.msg.auto.Struct.ServerInfoOrBuilder getServerInfosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.empire.msg.auto.sc.SCServerListMsg}
   */
  public static final class SCServerListMsg extends
      com.google.protobuf.GeneratedMessage
      implements SCServerListMsgOrBuilder {
    // Use SCServerListMsg.newBuilder() to construct.
    private SCServerListMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SCServerListMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SCServerListMsg defaultInstance;
    public static SCServerListMsg getDefaultInstance() {
      return defaultInstance;
    }

    public SCServerListMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SCServerListMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                serverInfos_ = new java.util.ArrayList<com.empire.msg.auto.Struct.ServerInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              serverInfos_.add(input.readMessage(com.empire.msg.auto.Struct.ServerInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          serverInfos_ = java.util.Collections.unmodifiableList(serverInfos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.empire.msg.auto.sc.SCSCServerListMsg.internal_static_com_empire_msg_auto_sc_SCServerListMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.empire.msg.auto.sc.SCSCServerListMsg.internal_static_com_empire_msg_auto_sc_SCServerListMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg.class, com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<SCServerListMsg> PARSER =
        new com.google.protobuf.AbstractParser<SCServerListMsg>() {
      public SCServerListMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCServerListMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SCServerListMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;
    public static final int SERVERINFOS_FIELD_NUMBER = 2;
    private java.util.List<com.empire.msg.auto.Struct.ServerInfo> serverInfos_;
    /**
     * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
     */
    public java.util.List<com.empire.msg.auto.Struct.ServerInfo> getServerInfosList() {
      return serverInfos_;
    }
    /**
     * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
     */
    public java.util.List<? extends com.empire.msg.auto.Struct.ServerInfoOrBuilder> 
        getServerInfosOrBuilderList() {
      return serverInfos_;
    }
    /**
     * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
     */
    public int getServerInfosCount() {
      return serverInfos_.size();
    }
    /**
     * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
     */
    public com.empire.msg.auto.Struct.ServerInfo getServerInfos(int index) {
      return serverInfos_.get(index);
    }
    /**
     * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
     */
    public com.empire.msg.auto.Struct.ServerInfoOrBuilder getServerInfosOrBuilder(
        int index) {
      return serverInfos_.get(index);
    }

    private void initFields() {
      id_ = 0;
      serverInfos_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      for (int i = 0; i < serverInfos_.size(); i++) {
        output.writeMessage(2, serverInfos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      for (int i = 0; i < serverInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, serverInfos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.empire.msg.auto.sc.SCServerListMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.empire.msg.auto.sc.SCSCServerListMsg.internal_static_com_empire_msg_auto_sc_SCServerListMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.empire.msg.auto.sc.SCSCServerListMsg.internal_static_com_empire_msg_auto_sc_SCServerListMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg.class, com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg.Builder.class);
      }

      // Construct using com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getServerInfosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (serverInfosBuilder_ == null) {
          serverInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          serverInfosBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.empire.msg.auto.sc.SCSCServerListMsg.internal_static_com_empire_msg_auto_sc_SCServerListMsg_descriptor;
      }

      public com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg getDefaultInstanceForType() {
        return com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg.getDefaultInstance();
      }

      public com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg build() {
        com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg buildPartial() {
        com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg result = new com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (serverInfosBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            serverInfos_ = java.util.Collections.unmodifiableList(serverInfos_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.serverInfos_ = serverInfos_;
        } else {
          result.serverInfos_ = serverInfosBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg) {
          return mergeFrom((com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg other) {
        if (other == com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (serverInfosBuilder_ == null) {
          if (!other.serverInfos_.isEmpty()) {
            if (serverInfos_.isEmpty()) {
              serverInfos_ = other.serverInfos_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureServerInfosIsMutable();
              serverInfos_.addAll(other.serverInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.serverInfos_.isEmpty()) {
            if (serverInfosBuilder_.isEmpty()) {
              serverInfosBuilder_.dispose();
              serverInfosBuilder_ = null;
              serverInfos_ = other.serverInfos_;
              bitField0_ = (bitField0_ & ~0x00000002);
              serverInfosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getServerInfosFieldBuilder() : null;
            } else {
              serverInfosBuilder_.addAllMessages(other.serverInfos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.empire.msg.auto.sc.SCSCServerListMsg.SCServerListMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 id = 1;
      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;
      private java.util.List<com.empire.msg.auto.Struct.ServerInfo> serverInfos_ =
        java.util.Collections.emptyList();
      private void ensureServerInfosIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          serverInfos_ = new java.util.ArrayList<com.empire.msg.auto.Struct.ServerInfo>(serverInfos_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.empire.msg.auto.Struct.ServerInfo, com.empire.msg.auto.Struct.ServerInfo.Builder, com.empire.msg.auto.Struct.ServerInfoOrBuilder> serverInfosBuilder_;

      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public java.util.List<com.empire.msg.auto.Struct.ServerInfo> getServerInfosList() {
        if (serverInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(serverInfos_);
        } else {
          return serverInfosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public int getServerInfosCount() {
        if (serverInfosBuilder_ == null) {
          return serverInfos_.size();
        } else {
          return serverInfosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public com.empire.msg.auto.Struct.ServerInfo getServerInfos(int index) {
        if (serverInfosBuilder_ == null) {
          return serverInfos_.get(index);
        } else {
          return serverInfosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public Builder setServerInfos(
          int index, com.empire.msg.auto.Struct.ServerInfo value) {
        if (serverInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServerInfosIsMutable();
          serverInfos_.set(index, value);
          onChanged();
        } else {
          serverInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public Builder setServerInfos(
          int index, com.empire.msg.auto.Struct.ServerInfo.Builder builderForValue) {
        if (serverInfosBuilder_ == null) {
          ensureServerInfosIsMutable();
          serverInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          serverInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public Builder addServerInfos(com.empire.msg.auto.Struct.ServerInfo value) {
        if (serverInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServerInfosIsMutable();
          serverInfos_.add(value);
          onChanged();
        } else {
          serverInfosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public Builder addServerInfos(
          int index, com.empire.msg.auto.Struct.ServerInfo value) {
        if (serverInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServerInfosIsMutable();
          serverInfos_.add(index, value);
          onChanged();
        } else {
          serverInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public Builder addServerInfos(
          com.empire.msg.auto.Struct.ServerInfo.Builder builderForValue) {
        if (serverInfosBuilder_ == null) {
          ensureServerInfosIsMutable();
          serverInfos_.add(builderForValue.build());
          onChanged();
        } else {
          serverInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public Builder addServerInfos(
          int index, com.empire.msg.auto.Struct.ServerInfo.Builder builderForValue) {
        if (serverInfosBuilder_ == null) {
          ensureServerInfosIsMutable();
          serverInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          serverInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public Builder addAllServerInfos(
          java.lang.Iterable<? extends com.empire.msg.auto.Struct.ServerInfo> values) {
        if (serverInfosBuilder_ == null) {
          ensureServerInfosIsMutable();
          super.addAll(values, serverInfos_);
          onChanged();
        } else {
          serverInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public Builder clearServerInfos() {
        if (serverInfosBuilder_ == null) {
          serverInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          serverInfosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public Builder removeServerInfos(int index) {
        if (serverInfosBuilder_ == null) {
          ensureServerInfosIsMutable();
          serverInfos_.remove(index);
          onChanged();
        } else {
          serverInfosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public com.empire.msg.auto.Struct.ServerInfo.Builder getServerInfosBuilder(
          int index) {
        return getServerInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public com.empire.msg.auto.Struct.ServerInfoOrBuilder getServerInfosOrBuilder(
          int index) {
        if (serverInfosBuilder_ == null) {
          return serverInfos_.get(index);  } else {
          return serverInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public java.util.List<? extends com.empire.msg.auto.Struct.ServerInfoOrBuilder> 
           getServerInfosOrBuilderList() {
        if (serverInfosBuilder_ != null) {
          return serverInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(serverInfos_);
        }
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public com.empire.msg.auto.Struct.ServerInfo.Builder addServerInfosBuilder() {
        return getServerInfosFieldBuilder().addBuilder(
            com.empire.msg.auto.Struct.ServerInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public com.empire.msg.auto.Struct.ServerInfo.Builder addServerInfosBuilder(
          int index) {
        return getServerInfosFieldBuilder().addBuilder(
            index, com.empire.msg.auto.Struct.ServerInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.empire.msg.auto.ServerInfo serverInfos = 2;</code>
       */
      public java.util.List<com.empire.msg.auto.Struct.ServerInfo.Builder> 
           getServerInfosBuilderList() {
        return getServerInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.empire.msg.auto.Struct.ServerInfo, com.empire.msg.auto.Struct.ServerInfo.Builder, com.empire.msg.auto.Struct.ServerInfoOrBuilder> 
          getServerInfosFieldBuilder() {
        if (serverInfosBuilder_ == null) {
          serverInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.empire.msg.auto.Struct.ServerInfo, com.empire.msg.auto.Struct.ServerInfo.Builder, com.empire.msg.auto.Struct.ServerInfoOrBuilder>(
                  serverInfos_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          serverInfos_ = null;
        }
        return serverInfosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.empire.msg.auto.sc.SCServerListMsg)
    }

    static {
      defaultInstance = new SCServerListMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.empire.msg.auto.sc.SCServerListMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_empire_msg_auto_sc_SCServerListMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_empire_msg_auto_sc_SCServerListMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030SC.SCServerListMsg.proto\022\026com.empire.m" +
      "sg.auto.sc\032\014struct.proto\"S\n\017SCServerList" +
      "Msg\022\n\n\002id\030\001 \001(\005\0224\n\013serverInfos\030\002 \003(\0132\037.c" +
      "om.empire.msg.auto.ServerInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_empire_msg_auto_sc_SCServerListMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_empire_msg_auto_sc_SCServerListMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_empire_msg_auto_sc_SCServerListMsg_descriptor,
              new java.lang.String[] { "Id", "ServerInfos", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.empire.msg.auto.Struct.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
